language: node_js
node_js:
  - "8"
cache: npm
env:
  global:
  - REACT_APP_API_KEY = $REACT_APP_API_KEY
  - REACT_APP_AUTH_DOMAIN = $REACT_APP_AUTH_DOMAIN
  - REACT_APP_DATABASE_URL = $REACT_APP_DATABASE_URL
  - REACT_APP_PROJECT_ID = $REACT_APP_PROJECT_ID
  - REACT_APP_STORAGE_BUCKET = ""
  - REACT_APP_MESSAGING_SENDER_ID = $REACT_APP_MESSAGING_SENDER_ID
  - REACT_APP_CLOUD_FUNCTION_BASE_URL = $REACT_APP_CLOUD_FUNCTION_BASE_URL

before_script:
  - npm install

script:
  - npm test -- --coverage

# after_success:
#   - npm run build

before_deploy:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch:
      - master