export const AUTH_MODULE = 'AUTH_MODULE'
export const COMMON_MODULE = 'COMMON_MODULE'

const actionTypes = {
  [AUTH_MODULE]: {
    LOGIN: `${AUTH_MODULE}/LOGIN`,
    IS_LOADING: `${AUTH_MODULE}/IS_LOADING`,
    ERROR_AUTH: `${AUTH_MODULE}/ERROR_AUTH`,
  },
  [COMMON_MODULE]: {
    CHANGE_LOCATION: `${COMMON_MODULE}/CHANGE_LOCATION`,
    ERROR_CHANGE_LOCATION: `${COMMON_MODULE}/ERROR_CHANGE_LOCATION`,
  },
}

export { actionTypes }
